import { describe, expect, it, vi } from "vitest";
import { schemawiseApi, SchemaWiseApiError } from "../../api/schemawise-api";
import { explainBcnf, explainSecondNormalForm, explainThirdNormalForm, ONE_NF_NOTICE } from "../explanations/explanation-builders";
import { formatAttributeSet, formatClosure, formatFunctionalDependency, formatRelation } from "./schema-formatters";
import { createInitialWorkspaceState, draftToSchemaRequest, workspaceReducer } from "./workspace-reducer";
import { sameFunctionalDependency, validateDraft } from "./workspace-validation";

const A = { id: "a", name: "A" }, B = { id: "b", name: "B" }, C = { id: "c", name: "C" };
const draft = { relationName: "R", attributes: [A, B, C], functionalDependencies: [{ left: ["a"], right: ["b"] }] };
const request = { relation: { name: "R", attributes: [A, B, C] }, functionalDependencies: draft.functionalDependencies };
const response = { relation: { name: "R", attributes: [A, B, C] }, candidateKeys: [["a"]], primeAttributes: ["a"], minimalCover: [], normalForms: { second: { satisfied: true, violations: [] }, third: { satisfied: true, violations: [] }, bcnf: { satisfied: true, violations: [] } } };

describe("schemawise API client", () => {
  it("posts JSON to the v1 analysis endpoint and parses success", async () => { const fetchMock = vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(JSON.stringify(response), { status: 200 })); await expect(schemawiseApi.analyzeSchema(request)).resolves.toEqual(response); expect(fetchMock).toHaveBeenCalledWith("http://127.0.0.1:3000/api/v1/analysis", expect.objectContaining({ method: "POST", body: JSON.stringify(request) })); fetchMock.mockRestore(); });
  it("normalizes contractual, network and abort failures", async () => { const fetchMock = vi.spyOn(globalThis, "fetch"); fetchMock.mockResolvedValueOnce(new Response(JSON.stringify({ error: { code: "INVALID_REQUEST", message: "bad", details: { field: "x" } } }), { status: 400 })); await expect(schemawiseApi.analyzeSchema(request)).rejects.toMatchObject({ kind: "api", code: "INVALID_REQUEST", status: 400 }); fetchMock.mockRejectedValueOnce(new TypeError("offline")); await expect(schemawiseApi.analyzeSchema(request)).rejects.toMatchObject({ kind: "network" }); const controller = new AbortController(); controller.abort(); fetchMock.mockRejectedValueOnce(new DOMException("aborted", "AbortError")); await expect(schemawiseApi.analyzeSchema(request, controller.signal)).rejects.toMatchObject({ kind: "aborted" }); fetchMock.mockRestore(); });
  it("centralizes all five operation paths", async () => { const fetchMock = vi.spyOn(globalThis, "fetch").mockImplementation(async () => new Response(JSON.stringify(response), { status: 200 })); await schemawiseApi.calculateClosure({ ...request, attributes: ["a"] }); await schemawiseApi.synthesizeThirdNormalForm(request); await schemawiseApi.decomposeBoyceCodd(request); await schemawiseApi.analyzeDependencyPreservation({ ...request, decomposition: [["a"]] }); expect(fetchMock.mock.calls.map(([url]) => url)).toEqual(["http://127.0.0.1:3000/api/v1/closure", "http://127.0.0.1:3000/api/v1/synthesis/3nf", "http://127.0.0.1:3000/api/v1/decomposition/bcnf", "http://127.0.0.1:3000/api/v1/analysis/dependency-preservation"]); fetchMock.mockRestore(); });
});

describe("workspace reducer", () => {
  it("supports attribute and FD mutations and cleans references", () => { let s = createInitialWorkspaceState(); s = workspaceReducer(s, { type: "addAttribute", attribute: A }); s = workspaceReducer(s, { type: "addAttribute", attribute: B }); s = workspaceReducer(s, { type: "renameAttribute", id: "b", name: "Beta" }); s = workspaceReducer(s, { type: "addFunctionalDependency", dependency: { left: ["a"], right: ["b"] } }); s = workspaceReducer(s, { type: "updateFunctionalDependency", index: 0, dependency: { left: ["b"], right: ["a"] } }); expect(s.draft.functionalDependencies).toEqual([{ left: ["b"], right: ["a"] }]); s = workspaceReducer(s, { type: "removeAttribute", id: "a" }); expect(s.draft.attributes).toEqual([{ ...B, name: "Beta" }]); expect(s.draft.functionalDependencies).toEqual([]); s = workspaceReducer(s, { type: "removeFunctionalDependency", index: 0 }); expect(s.draft.functionalDependencies).toEqual([]); expect(s.revision).toBe(7); });
  it("loads the deterministic example without requesting analysis", () => { const s = workspaceReducer(createInitialWorkspaceState(), { type: "loadExample", ids: { a: "a", b: "b", c: "c" } }); expect(s.draft).toEqual({ relationName: "R", attributes: [A, B, C], functionalDependencies: [{ left: ["a"], right: ["b"] }, { left: ["b"], right: ["c"] }] }); expect(s.analysis.status).toBe("idle"); });
  it("keeps the analyzed snapshot and rejects stale async responses", () => { let s = workspaceReducer(createInitialWorkspaceState(), { type: "loadExample", ids: { a: "a", b: "b", c: "c" } }); const analyzed = draftToSchemaRequest(s.draft); s = workspaceReducer(s, { type: "analysisRequestStart", requestId: "old", inputRevision: s.revision, inputSnapshot: analyzed }); s = workspaceReducer(s, { type: "analysisSuccess", requestId: "old", data: response }); s = workspaceReducer(s, { type: "changeRelationName", name: "Changed" }); expect(s.analysis.outOfDate).toBe(true); expect(s.analysis.inputSnapshot).toEqual(analyzed); const next = draftToSchemaRequest(s.draft); s = workspaceReducer(s, { type: "analysisRequestStart", requestId: "new", inputRevision: s.revision, inputSnapshot: next }); expect(workspaceReducer(s, { type: "analysisSuccess", requestId: "old", data: response })).toBe(s); });
  it("binds a response to the snapshot captured at request start even if the draft changes in flight", () => { let s = workspaceReducer(createInitialWorkspaceState(), { type: "loadExample", ids: { a: "a", b: "b", c: "c" } }); const analyzed = draftToSchemaRequest(s.draft); const analyzedRevision = s.revision; s = workspaceReducer(s, { type: "analysisRequestStart", requestId: "a", inputRevision: analyzedRevision, inputSnapshot: analyzed }); s = workspaceReducer(s, { type: "renameAttribute", id: "a", name: "Changed" }); s = workspaceReducer(s, { type: "analysisSuccess", requestId: "a", data: response }); expect(s.analysis.inputRevision).toBe(analyzedRevision); expect(s.analysis.inputSnapshot).toEqual(analyzed); expect(s.analysis.outOfDate).toBe(true); });
  it("makes transformations source the analyzed snapshot", () => { let s = workspaceReducer(createInitialWorkspaceState(), { type: "loadExample", ids: { a: "a", b: "b", c: "c" } }); const input = draftToSchemaRequest(s.draft); s = workspaceReducer(s, { type: "analysisRequestStart", requestId: "a", inputRevision: s.revision, inputSnapshot: input }); s = workspaceReducer(s, { type: "analysisSuccess", requestId: "a", data: response }); s = workspaceReducer(s, { type: "changeRelationName", name: "new draft" }); s = workspaceReducer(s, { type: "synthesisRequestStart", requestId: "s" }); expect(s.synthesis.inputSnapshot?.relation.name).toBe("R"); expect(s.synthesis.sourceRevision).toBe(1); });
});

describe("validation and formatters", () => {
  it("enforces limits, duplicate visual names, references and order-independent FD equality", () => { expect(validateDraft({ ...draft, relationName: " " })).toEqual(expect.arrayContaining([expect.objectContaining({ field: "relationName" })])); expect(validateDraft({ ...draft, attributes: [...draft.attributes, ...Array.from({ length: 4 }, (_, i) => ({ id: `x${i}`, name: `X${i}` }))] })).toEqual(expect.arrayContaining([expect.objectContaining({ field: "attributes" })])); expect(validateDraft({ ...draft, attributes: [A, { id: "x", name: " customer " }, { id: "y", name: "CUSTOMER" }] })).toEqual(expect.arrayContaining([expect.objectContaining({ field: "attribute:y" })])); expect(sameFunctionalDependency({ left: ["a", "b"], right: ["c"] }, { left: ["b", "a"], right: ["c"] })).toBe(true); expect(validateDraft({ ...draft, functionalDependencies: Array.from({ length: 13 }, () => ({ left: [], right: [] })) })).toEqual(expect.arrayContaining([expect.objectContaining({ field: "functionalDependencies" })])); expect(validateDraft({ ...draft, functionalDependencies: [{ left: [], right: [] }] })).toEqual([]); });
  it("keeps relation and attribute names within the API contract limit", () => { expect(validateDraft({ ...draft, relationName: "R".repeat(121) })).toEqual(expect.arrayContaining([expect.objectContaining({ field: "relationName" })])); expect(validateDraft({ ...draft, attributes: [{ id: "a", name: "A".repeat(121) }] })).toEqual(expect.arrayContaining([expect.objectContaining({ field: "attribute:a" })])); });
  it("formats empty sets, schema-ordered sets, FDs, closures and relations", () => { const lookup = new Map([["a", "A"], ["b", "B"]]); expect(formatAttributeSet([], lookup)).toBe("∅"); expect(formatAttributeSet(["b", "a"], lookup)).toBe("{A, B}"); expect(formatFunctionalDependency({ left: [], right: ["a"] }, lookup)).toBe("∅ → A"); expect(formatFunctionalDependency({ left: ["a"], right: [] }, lookup)).toBe("A → ∅"); expect(formatClosure(["b", "a"], lookup)).toBe("{A, B}"); expect(formatRelation(request)).toBe("R(A, B, C)"); });
});

describe("deterministic explanations", () => {
  it("builds 2NF, 3NF, BCNF and 1NF semantic copy", () => { const lookup = new Map([["a", "A"], ["b", "B"], ["c", "C"]]); expect(explainSecondNormalForm({ candidateKey: ["a", "b"], determinant: ["a"], dependent: "c" }, lookup, request).reasons).toContain("Candidate key: {A, B}"); expect(explainThirdNormalForm({ determinant: ["b"], dependent: "c" }, ["a"], lookup, request).reasons).toContain("C is not a prime attribute."); expect(explainBcnf({ determinant: ["b"], dependent: "c" }, lookup, request).reasons[1]).toContain("BCNF"); expect(ONE_NF_NOTICE).not.toContain("1NF:"); });
});

void SchemaWiseApiError;
